### ISSUE TITLE
VisDial v0.9

### ISSUE THREAD

**Issue by ChoYS96** [batra-mlp-lab/visdial-challenge-starter-pytorch#3]
Hello.
I want to use VisDial v0.9.  
So, I  run  the prepro.py  -version 0.9 and I got the visdial_datta.h5  and visdial_params.json.
But, when I run the train.py, I got this  error.
What can I dot to  solve this problem?

Traceback (most recent call last):
  File "train.py", line 146, in <module>
    for i, batch in enumerate(dataloader):
  File "/home/ailab/anaconda2/envs/visdial-chal/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 188, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/ailab/anaconda2/envs/visdial-chal/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 188, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/ailab/visdial-challenge-starter-pytorch/dataloader.py", line 164, in __getitem__
    item['num_rounds'] = self.data[dtype + '_num_rounds'][idx]
IndexError: index 87666 is out of range for dimension 0 (of size 82783)

**Comment by abhshkdz** [comment]
Are you sure you're using image features corresponding to v0.9? For example, downloaded from this folder: https://computing.ece.vt.edu/\~abhshkdz/visdial/data/v0.9/.

**Comment by ChoYS96** [comment]
Thank you for replying!
